import google from "../assets/Google.png";
import logo from "../assets/Purple.png";
import loginBg from "../assets/logibg.png";
import joinUs from "../assets/joinus.png";
import signbg from "../assets/signbg.png";
import signAvatar from "../assets/signavatar.png";
import Errorimg from "../assets/Error.png";
import Lock from "../assets/lock.png";
import otps from "../assets/otp.png";

export { google };
export { logo };
export { loginBg };
export { joinUs };
export { signAvatar };
export { signbg };
export { Errorimg };
export { Lock };
export { otps };
